(setq elfeed-feeds
    '(("http://nullprogram.com/feed/" emacs)
        ("https://www.booleanknot.com/blog/feed.xml" emacs important)
        ("https://labs.uswitch.com/rss/" programming)
        ("http://howardism.org/Technical/Emacs/index.xml" emacs)
        ("http://blog.fogus.me/feed/" clojure)
        ("https://blog.panter.ch/feed.xml" rails)
        ("http://planet.emacsen.org/atom.xml" emacs)
        ("https://emacsair.me/feed.xml" emacs)
        ("http://200ok.ch/atom.xml" 200ok)))
